apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-example
  namespace: staging
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: jxRequirements.ingress.domain
          value: 35.202.17.57.nip.io
    path: charts/node-example
    repoURL: https://github.com/jstrachan/node-example.git
    targetRevision: v0.0.38
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
